-- ============================================================
-- CORE TABLES — tenants, users, patients, appointments,
--               invoices, lab_orders (with LabOrderStatus enum)
-- These were generated by prisma db push but never captured
-- in a migration file. This migration creates them safely
-- using IF NOT EXISTS so it is idempotent.
-- ============================================================

-- Enums (PostgreSQL requires these before the tables that use them)
DO $$ BEGIN
  CREATE TYPE "TenantType" AS ENUM (
    'HOSPITAL','CLINIC','DIAGNOSTIC_CENTER','IVF_CENTER',
    'PHARMACY','INDIVIDUAL_DOCTOR','HOME_HEALTHCARE',
    'MEDICAL_EQUIPMENT'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "TenantStatus" AS ENUM ('ACTIVE','SUSPENDED','TRIAL','CHURNED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "UserRole" AS ENUM (
    'TENANT_ADMIN','BRANCH_ADMIN','DOCTOR','RECEPTIONIST',
    'BILLING_STAFF','MARKETING_USER','LAB_TECHNICIAN',
    'PHARMACIST','NURSE','SUPER_ADMIN'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "AppointmentStatus" AS ENUM (
    'SCHEDULED','CONFIRMED','CHECKED_IN','IN_PROGRESS',
    'COMPLETED','CANCELLED','NO_SHOW','RESCHEDULED'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "AppointmentType" AS ENUM (
    'SCHEDULED','WALK_IN','EMERGENCY','TELECONSULTATION'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "InvoiceStatus" AS ENUM (
    'DRAFT','SENT','PARTIALLY_PAID','PAID','OVERDUE','CANCELLED','REFUNDED'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "PaymentMethod" AS ENUM (
    'CASH','UPI','CARD','NET_BANKING','INSURANCE','WALLET','CHEQUE'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "LabOrderStatus" AS ENUM (
    'ORDERED','SAMPLE_COLLECTED','PROCESSING',
    'COMPLETED','DELIVERED','CANCELLED'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "LeadStage" AS ENUM (
    'NEW','CONTACTED','APPOINTMENT_BOOKED','VISITED',
    'FOLLOW_UP','ACTIVE_PATIENT','DORMANT','LOST'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "BedStatus" AS ENUM (
    'AVAILABLE','OCCUPIED','RESERVED','MAINTENANCE','CLEANING'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "ConversationStatus" AS ENUM (
    'OPEN','ASSIGNED','RESOLVED','WAITING'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ── Tenants ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "tenants" (
  "id"                TEXT          NOT NULL,
  "name"              TEXT          NOT NULL,
  "slug"              TEXT          NOT NULL,
  "type"              "TenantType"  NOT NULL DEFAULT 'HOSPITAL',
  "status"            "TenantStatus" NOT NULL DEFAULT 'TRIAL',
  "whatsapp_number"   TEXT,
  "whatsapp_token"    TEXT,
  "phone"             TEXT,
  "email"             TEXT,
  "address"           TEXT,
  "city"              TEXT,
  "state"             TEXT,
  "country"           TEXT          NOT NULL DEFAULT 'IN',
  "timezone"          TEXT          NOT NULL DEFAULT 'Asia/Kolkata',
  "currency"          TEXT          NOT NULL DEFAULT 'INR',
  "logo_url"          TEXT,
  "settings"          JSONB         NOT NULL DEFAULT '{}',
  "plan"              TEXT          NOT NULL DEFAULT 'starter',
  "trial_ends_at"     TIMESTAMP(3),
  "subscription_ends_at" TIMESTAMP(3),
  "portal_family_id"  TEXT,
  "sub_type_id"       TEXT,
  "created_at"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at"        TIMESTAMP(3),
  CONSTRAINT "tenants_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "tenants_slug_key" ON "tenants"("slug");

-- ── Branches ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "branches" (
  "id"         TEXT NOT NULL,
  "tenant_id"  TEXT NOT NULL,
  "name"       TEXT NOT NULL,
  "address"    TEXT,
  "city"       TEXT,
  "state"      TEXT,
  "country"    TEXT NOT NULL DEFAULT 'IN',
  "phone"      TEXT,
  "email"      TEXT,
  "is_active"  BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "branches_pkey" PRIMARY KEY ("id")
);

-- ── Departments ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "departments" (
  "id"         TEXT NOT NULL,
  "tenant_id"  TEXT NOT NULL,
  "branch_id"  TEXT,
  "name"       TEXT NOT NULL,
  "type"       TEXT NOT NULL DEFAULT 'clinical',
  "is_active"  BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "departments_pkey" PRIMARY KEY ("id")
);

-- ── Users ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "users" (
  "id"            TEXT      NOT NULL,
  "tenant_id"     TEXT      NOT NULL,
  "email"         TEXT      NOT NULL,
  "phone"         TEXT,
  "password_hash" TEXT      NOT NULL,
  "first_name"    TEXT      NOT NULL,
  "last_name"     TEXT,
  "role"          "UserRole" NOT NULL DEFAULT 'RECEPTIONIST',
  "branch_ids"    TEXT[]    NOT NULL DEFAULT '{}',
  "permissions"   JSONB     NOT NULL DEFAULT '{}',
  "is_active"     BOOLEAN   NOT NULL DEFAULT true,
  "last_login_at" TIMESTAMP(3),
  "created_at"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "users_tenant_id_email_key" ON "users"("tenant_id","email");

-- ── Platform Admins ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "platform_admins" (
  "id"            TEXT NOT NULL,
  "email"         TEXT NOT NULL,
  "password_hash" TEXT NOT NULL,
  "first_name"    TEXT NOT NULL,
  "last_name"     TEXT,
  "role"          TEXT NOT NULL DEFAULT 'SUPER_ADMIN',
  "is_active"     BOOLEAN NOT NULL DEFAULT true,
  "last_login_at" TIMESTAMP(3),
  "created_at"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "platform_admins_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "platform_admins_email_key" ON "platform_admins"("email");

-- ── Doctors ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "doctors" (
  "id"                TEXT NOT NULL,
  "tenant_id"         TEXT NOT NULL,
  "user_id"           TEXT,
  "first_name"        TEXT NOT NULL,
  "last_name"         TEXT,
  "specialties"       TEXT[] NOT NULL DEFAULT '{}',
  "registration_no"   TEXT,
  "phone"             TEXT,
  "email"             TEXT,
  "consultation_fee"  INTEGER NOT NULL DEFAULT 0,
  "department_ids"    TEXT[] NOT NULL DEFAULT '{}',
  "branch_ids"        TEXT[] NOT NULL DEFAULT '{}',
  "bio"               TEXT,
  "photo_url"         TEXT,
  "is_active"         BOOLEAN NOT NULL DEFAULT true,
  "created_at"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "doctors_pkey" PRIMARY KEY ("id")
);

-- ── Patients ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "patients" (
  "id"             TEXT NOT NULL,
  "tenant_id"      TEXT NOT NULL,
  "health_id"      TEXT,
  "first_name"     TEXT NOT NULL,
  "last_name"      TEXT,
  "phone"          TEXT NOT NULL,
  "email"          TEXT,
  "date_of_birth"  TIMESTAMP(3),
  "gender"         TEXT,
  "blood_group"    TEXT,
  "address"        TEXT,
  "city"           TEXT,
  "state"          TEXT,
  "country"        TEXT NOT NULL DEFAULT 'IN',
  "insurance_id"   TEXT,
  "insurance_provider" TEXT,
  "tags"           TEXT[] NOT NULL DEFAULT '{}',
  "notes"          TEXT,
  "last_visit_at"  TIMESTAMP(3),
  "is_active"      BOOLEAN NOT NULL DEFAULT true,
  "created_at"     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at"     TIMESTAMP(3),
  CONSTRAINT "patients_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "patients_tenant_id_phone_key" ON "patients"("tenant_id","phone");
CREATE INDEX IF NOT EXISTS "patients_tenant_id_idx" ON "patients"("tenant_id");

-- ── Appointments ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "appointments" (
  "id"           TEXT NOT NULL,
  "tenant_id"    TEXT NOT NULL,
  "patient_id"   TEXT NOT NULL,
  "doctor_id"    TEXT,
  "branch_id"    TEXT,
  "department_id" TEXT,
  "slot_time"    TIMESTAMP(3) NOT NULL,
  "duration_mins" INTEGER NOT NULL DEFAULT 15,
  "status"       "AppointmentStatus" NOT NULL DEFAULT 'SCHEDULED',
  "type"         "AppointmentType"   NOT NULL DEFAULT 'SCHEDULED',
  "reason"       TEXT,
  "notes"        TEXT,
  "token_number" INTEGER,
  "checked_in_at" TIMESTAMP(3),
  "completed_at"  TIMESTAMP(3),
  "cancelled_at"  TIMESTAMP(3),
  "reminder_sent" BOOLEAN NOT NULL DEFAULT false,
  "created_at"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "appointments_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "appointments_tenant_id_slot_time_idx" ON "appointments"("tenant_id","slot_time");

-- ── Visits ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "visits" (
  "id"             TEXT NOT NULL,
  "tenant_id"      TEXT NOT NULL,
  "patient_id"     TEXT NOT NULL,
  "appointment_id" TEXT,
  "doctor_id"      TEXT,
  "chief_complaint" TEXT,
  "diagnosis"      TEXT[] NOT NULL DEFAULT '{}',
  "notes"          TEXT,
  "vitals"         JSONB,
  "prescriptions"  JSONB,
  "follow_up_date" TIMESTAMP(3),
  "rating"         INTEGER,
  "feedback"       TEXT,
  "nps_score"      INTEGER,
  "created_at"     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "visits_pkey" PRIMARY KEY ("id")
);

-- ── Invoices ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "invoices" (
  "id"             TEXT NOT NULL,
  "tenant_id"      TEXT NOT NULL,
  "patient_id"     TEXT NOT NULL,
  "visit_id"       TEXT,
  "invoice_number" TEXT NOT NULL,
  "items"          JSONB NOT NULL DEFAULT '[]',
  "subtotal"       INTEGER NOT NULL DEFAULT 0,
  "discount"       INTEGER NOT NULL DEFAULT 0,
  "tax"            INTEGER NOT NULL DEFAULT 0,
  "total_amount"   INTEGER NOT NULL DEFAULT 0,
  "paid_amount"    INTEGER NOT NULL DEFAULT 0,
  "status"         "InvoiceStatus" NOT NULL DEFAULT 'DRAFT',
  "due_date"       TIMESTAMP(3),
  "notes"          TEXT,
  "created_at"     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "invoices_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "invoices_tenant_id_invoice_number_key" ON "invoices"("tenant_id","invoice_number");

-- ── Lab Orders ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "lab_orders" (
  "id"                TEXT           NOT NULL,
  "tenant_id"         TEXT           NOT NULL,
  "patient_id"        TEXT           NOT NULL,
  "doctor_id"         TEXT,
  "order_number"      TEXT           NOT NULL,
  "tests"             JSONB          NOT NULL DEFAULT '[]',
  "status"            "LabOrderStatus" NOT NULL DEFAULT 'ORDERED',
  "sample_collected_at" TIMESTAMP(3),
  "reported_at"       TIMESTAMP(3),
  "report_url"        TEXT,
  "report_delivered"  BOOLEAN        NOT NULL DEFAULT false,
  "notes"             TEXT,
  "priority"          TEXT           NOT NULL DEFAULT 'normal',
  "wa_sent"           BOOLEAN        NOT NULL DEFAULT false,
  "sample_barcode"    TEXT,
  "referring_doctor"  TEXT,
  "clinical_info"     TEXT,
  "department_id"     TEXT,
  "created_at"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "lab_orders_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "lab_orders_tenant_id_order_number_key" ON "lab_orders"("tenant_id","order_number");

-- ── Payments ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "payments" (
  "id"           TEXT NOT NULL,
  "tenant_id"    TEXT NOT NULL,
  "invoice_id"   TEXT NOT NULL,
  "amount"       INTEGER NOT NULL,
  "method"       "PaymentMethod" NOT NULL DEFAULT 'CASH',
  "gateway_ref"  TEXT,
  "status"       TEXT NOT NULL DEFAULT 'completed',
  "notes"        TEXT,
  "created_at"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "payments_pkey" PRIMARY KEY ("id")
);

-- ── Leads ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "leads" (
  "id"          TEXT NOT NULL,
  "tenant_id"   TEXT NOT NULL,
  "patient_id"  TEXT,
  "source"      TEXT NOT NULL DEFAULT 'whatsapp',
  "stage"       "LeadStage" NOT NULL DEFAULT 'NEW',
  "assigned_to" TEXT,
  "campaign_id" TEXT,
  "notes"       TEXT,
  "tags"        TEXT[] NOT NULL DEFAULT '{}',
  "created_at"  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "leads_pkey" PRIMARY KEY ("id")
);

-- ── Conversations ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "conversations" (
  "id"              TEXT NOT NULL,
  "tenant_id"       TEXT NOT NULL,
  "patient_id"      TEXT,
  "wa_phone"        TEXT NOT NULL,
  "status"          "ConversationStatus" NOT NULL DEFAULT 'OPEN',
  "assigned_to"     TEXT,
  "last_message_at" TIMESTAMP(3),
  "messages_count"  INTEGER NOT NULL DEFAULT 0,
  "tags"            TEXT[] NOT NULL DEFAULT '{}',
  "created_at"      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "conversations_pkey" PRIMARY KEY ("id")
);

-- ── Beds ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "beds" (
  "id"          TEXT NOT NULL,
  "tenant_id"   TEXT NOT NULL,
  "branch_id"   TEXT,
  "ward"        TEXT NOT NULL,
  "category"    TEXT NOT NULL DEFAULT 'general',
  "number"      TEXT NOT NULL,
  "status"      "BedStatus" NOT NULL DEFAULT 'AVAILABLE',
  "patient_id"  TEXT,
  "floor"       TEXT,
  "notes"       TEXT,
  "created_at"  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "beds_pkey" PRIMARY KEY ("id")
);

-- ── Refresh Tokens ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "refresh_tokens" (
  "id"         TEXT NOT NULL,
  "user_id"    TEXT NOT NULL,
  "tenant_id"  TEXT NOT NULL,
  "token"      TEXT NOT NULL,
  "expires_at" TIMESTAMP(3) NOT NULL,
  "revoked"    BOOLEAN NOT NULL DEFAULT false,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "refresh_tokens_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "refresh_tokens_token_key" ON "refresh_tokens"("token");
