-- ============================================
-- HospiBot Rebuild Batch 1 + 2 Migration
-- Run in Supabase SQL Editor
-- 10 new tables for research-backed features
-- ============================================

-- 1. Radiotracer Log (AERB SC-2)
CREATE TABLE IF NOT EXISTS radiotracer_logs (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
  tenant_id TEXT NOT NULL,
  patient_id TEXT,
  patient_name TEXT NOT NULL,
  patient_age INTEGER,
  patient_weight DOUBLE PRECISION,
  tracer_name TEXT NOT NULL,
  radioisotope TEXT,
  half_life_minutes DOUBLE PRECISION,
  route_of_admin TEXT,
  batch_number TEXT NOT NULL,
  supplier_name TEXT,
  received_date TIMESTAMPTZ,
  received_activity_mbq DOUBLE PRECISION,
  expiry_date TIMESTAMPTZ,
  calibration_activity_mbq DOUBLE PRECISION,
  calibration_time TIMESTAMPTZ,
  administration_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  administration_time TIMESTAMPTZ,
  administered_dose_mbq DOUBLE PRECISION,
  decayed_activity_mbq DOUBLE PRECISION,
  residual_in_syringe_mbq DOUBLE PRECISION,
  dose_calibrator TEXT,
  dose_calib_serial_no TEXT,
  elora_license_no TEXT,
  rso_verified BOOLEAN DEFAULT FALSE,
  rso_name TEXT,
  waste_disposal_method TEXT,
  waste_activity_mbq DOUBLE PRECISION,
  indication TEXT,
  scan_type TEXT,
  adverse_reaction TEXT,
  nuclear_physician TEXT,
  technician_name TEXT,
  pregnancy_screened BOOLEAN DEFAULT FALSE,
  breastfeeding_status TEXT,
  notes TEXT,
  status TEXT DEFAULT 'administered',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_radiotracer_logs_tenant ON radiotracer_logs(tenant_id);
CREATE INDEX IF NOT EXISTS idx_radiotracer_logs_tracer ON radiotracer_logs(tenant_id, tracer_name);

-- 2. RSO Dashboard (AERB AE(RP) Rules 2004)
CREATE TABLE IF NOT EXISTS rso_dashboards (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
  tenant_id TEXT NOT NULL,
  record_type TEXT NOT NULL,
  staff_name TEXT,
  staff_id TEXT,
  designation TEXT,
  department TEXT,
  classified_worker BOOLEAN DEFAULT FALSE,
  badge_id TEXT,
  badge_type TEXT DEFAULT 'TLD',
  monitoring_period TEXT,
  period_start TIMESTAMPTZ,
  period_end TIMESTAMPTZ,
  dose_msv DOUBLE PRECISION,
  dose_hp10 DOUBLE PRECISION,
  dose_hp007 DOUBLE PRECISION,
  cumulative_annual_dose_msv DOUBLE PRECISION,
  five_year_avg_msv DOUBLE PRECISION,
  investigation_required BOOLEAN DEFAULT FALSE,
  aerb_alert TEXT,
  area_name TEXT,
  area_type TEXT,
  ambient_dose_rate DOUBLE PRECISION,
  ambient_dose_unit TEXT DEFAULT 'uSv/hr',
  incident_description TEXT,
  incident_date TIMESTAMPTZ,
  corrective_action TEXT,
  reported_to_aerb BOOLEAN DEFAULT FALSE,
  rso_name TEXT,
  rso_level TEXT,
  rso_cert_expiry TIMESTAMPTZ,
  survey_meter_used TEXT,
  calibration_date TIMESTAMPTZ,
  notes TEXT,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_rso_dashboards_tenant ON rso_dashboards(tenant_id);
CREATE INDEX IF NOT EXISTS idx_rso_dashboards_type ON rso_dashboards(tenant_id, record_type);

-- 3. TMT Stress Test (Bruce Protocol)
CREATE TABLE IF NOT EXISTS tmt_stress_tests (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
  tenant_id TEXT NOT NULL,
  patient_id TEXT,
  patient_name TEXT NOT NULL,
  patient_age INTEGER,
  patient_gender TEXT,
  patient_weight DOUBLE PRECISION,
  test_date TIMESTAMPTZ NOT NULL,
  protocol TEXT DEFAULT 'standard-bruce',
  indication TEXT,
  medications TEXT,
  resting_hr INTEGER,
  resting_sbp INTEGER,
  resting_dbp INTEGER,
  resting_ecg TEXT,
  max_stage_completed INTEGER,
  exercise_duration_min DOUBLE PRECISION,
  mets_achieved DOUBLE PRECISION,
  max_heart_rate INTEGER,
  target_heart_rate INTEGER,
  target_achieved BOOLEAN,
  peak_sbp INTEGER,
  peak_dbp INTEGER,
  reason_stopped TEXT,
  st_segment_changes TEXT,
  st_depression_mm DOUBLE PRECISION,
  st_depression_leads TEXT,
  st_onset_stage INTEGER,
  st_recovery_min DOUBLE PRECISION,
  arrhythmias TEXT,
  chest_pain BOOLEAN DEFAULT FALSE,
  chest_pain_onset TEXT,
  dyspnea BOOLEAN DEFAULT FALSE,
  dizziness BOOLEAN DEFAULT FALSE,
  recovery_hr_5min INTEGER,
  recovery_bp_5min TEXT,
  recovery_ecg_normal TEXT,
  overall_result TEXT,
  duke_score DOUBLE PRECISION,
  interpretation TEXT,
  recommendation TEXT,
  cardiologist TEXT,
  technician_name TEXT,
  emergency_equipment_checked BOOLEAN DEFAULT FALSE,
  defibrillator_available BOOLEAN DEFAULT FALSE,
  notes TEXT,
  status TEXT DEFAULT 'draft',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_tmt_stress_tenant ON tmt_stress_tests(tenant_id);
CREATE INDEX IF NOT EXISTS idx_tmt_stress_result ON tmt_stress_tests(tenant_id, overall_result);

-- 4. Holter Allocation (ISHNE-HRS 2017)
CREATE TABLE IF NOT EXISTS holter_allocations (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
  tenant_id TEXT NOT NULL,
  patient_id TEXT,
  patient_name TEXT NOT NULL,
  patient_age INTEGER,
  indication TEXT,
  referring_doctor TEXT,
  device_serial_no TEXT NOT NULL,
  device_model TEXT,
  lead_configuration TEXT DEFAULT '3-channel',
  duration TEXT DEFAULT '24h',
  issued_at TIMESTAMPTZ NOT NULL,
  expected_return TIMESTAMPTZ,
  returned_at TIMESTAMPTZ,
  device_status TEXT DEFAULT 'issued',
  device_condition TEXT,
  recording_quality TEXT,
  total_recorded_hours DOUBLE PRECISION,
  analyzable_percentage DOUBLE PRECISION,
  total_heartbeats INTEGER,
  avg_heart_rate INTEGER,
  min_heart_rate INTEGER,
  max_heart_rate INTEGER,
  pvc_count INTEGER,
  pac_count INTEGER,
  vent_tachy_episodes INTEGER,
  svt_episodes INTEGER,
  af_episodes INTEGER,
  af_burden_pct DOUBLE PRECISION,
  pauses_gt_2s INTEGER,
  longest_pause_sec DOUBLE PRECISION,
  st_changes TEXT,
  symptom_diary JSONB,
  symptom_correlation TEXT,
  sdnn DOUBLE PRECISION,
  rmssd DOUBLE PRECISION,
  interpretation TEXT,
  recommendation TEXT,
  cardiologist TEXT,
  technician_name TEXT,
  notes TEXT,
  status TEXT DEFAULT 'issued',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_holter_tenant ON holter_allocations(tenant_id);
CREATE INDEX IF NOT EXISTS idx_holter_device ON holter_allocations(tenant_id, device_status);

-- 5. ABPM Reports (ESH 2024)
CREATE TABLE IF NOT EXISTS abpm_reports (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
  tenant_id TEXT NOT NULL,
  patient_id TEXT,
  patient_name TEXT NOT NULL,
  patient_age INTEGER,
  patient_gender TEXT,
  study_date TIMESTAMPTZ NOT NULL,
  duration TEXT DEFAULT '24h',
  device_model TEXT,
  device_serial_no TEXT,
  total_readings INTEGER,
  valid_readings INTEGER,
  office_sbp DOUBLE PRECISION,
  office_dbp DOUBLE PRECISION,
  avg_24h_sbp DOUBLE PRECISION,
  avg_24h_dbp DOUBLE PRECISION,
  avg_24h_hr DOUBLE PRECISION,
  daytime_avg_sbp DOUBLE PRECISION,
  daytime_avg_dbp DOUBLE PRECISION,
  daytime_avg_hr DOUBLE PRECISION,
  nighttime_avg_sbp DOUBLE PRECISION,
  nighttime_avg_dbp DOUBLE PRECISION,
  nighttime_avg_hr DOUBLE PRECISION,
  dipping_pct DOUBLE PRECISION,
  dipping_status TEXT,
  daytime_sbp_load DOUBLE PRECISION,
  daytime_dbp_load DOUBLE PRECISION,
  nighttime_sbp_load DOUBLE PRECISION,
  nighttime_dbp_load DOUBLE PRECISION,
  morning_surge_sbp DOUBLE PRECISION,
  max_sbp DOUBLE PRECISION,
  max_dbp DOUBLE PRECISION,
  min_sbp DOUBLE PRECISION,
  min_dbp DOUBLE PRECISION,
  bp_phenotype TEXT,
  nocturnal_hypertension BOOLEAN,
  interpretation TEXT,
  recommendation TEXT,
  referring_doctor TEXT,
  reported_by TEXT,
  notes TEXT,
  status TEXT DEFAULT 'draft',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_abpm_tenant ON abpm_reports(tenant_id);
CREATE INDEX IF NOT EXISTS idx_abpm_dipping ON abpm_reports(tenant_id, dipping_status);
CREATE INDEX IF NOT EXISTS idx_abpm_phenotype ON abpm_reports(tenant_id, bp_phenotype);

-- 6. Sonologist Panel (PC-PNDT Act)
CREATE TABLE IF NOT EXISTS sonologist_panels (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
  tenant_id TEXT NOT NULL,
  sonologist_name TEXT NOT NULL,
  qualification TEXT NOT NULL,
  specialization TEXT,
  mci_registration TEXT NOT NULL,
  pcpndt_registration TEXT,
  pcpndt_reg_expiry TIMESTAMPTZ,
  places_registered INTEGER DEFAULT 1,
  place1_name TEXT,
  place1_district TEXT,
  place2_name TEXT,
  place2_district TEXT,
  machines_registered TEXT,
  locum_doctor BOOLEAN DEFAULT FALSE,
  locum_approval_date TIMESTAMPTZ,
  weekly_schedule JSONB,
  daily_scan_limit INTEGER,
  current_day_scans INTEGER DEFAULT 0,
  form_f_compliance BOOLEAN DEFAULT TRUE,
  quarterly_reports_due TEXT,
  phone TEXT,
  email TEXT,
  notes TEXT,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_sonologist_tenant ON sonologist_panels(tenant_id);

-- 7. Client Center (Teleradiology)
CREATE TABLE IF NOT EXISTS client_centers (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
  tenant_id TEXT NOT NULL,
  center_name TEXT NOT NULL,
  center_type TEXT,
  contact_person TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  city TEXT,
  state TEXT,
  contract_start TIMESTAMPTZ,
  contract_end TIMESTAMPTZ,
  contract_value DOUBLE PRECISION,
  billing_model TEXT DEFAULT 'per-study',
  modalities_supported TEXT,
  xray_rate DOUBLE PRECISION,
  ct_rate DOUBLE PRECISION,
  mri_rate DOUBLE PRECISION,
  usg_rate DOUBLE PRECISION,
  mammo_rate DOUBLE PRECISION,
  stat_sla_minutes INTEGER DEFAULT 30,
  routine_sla_minutes INTEGER DEFAULT 480,
  priority_sla_minutes INTEGER DEFAULT 180,
  monthly_volume_target INTEGER,
  pacs_integrated BOOLEAN DEFAULT FALSE,
  dicom_node_aet TEXT,
  vpn_configured BOOLEAN DEFAULT FALSE,
  notes TEXT,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_client_centers_tenant ON client_centers(tenant_id);

-- 8. SLA Alert (Teleradiology TAT)
CREATE TABLE IF NOT EXISTS sla_alerts (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
  tenant_id TEXT NOT NULL,
  client_id TEXT,
  client_name TEXT,
  study_accession TEXT NOT NULL,
  patient_name TEXT,
  modality TEXT,
  body_part TEXT,
  priority TEXT DEFAULT 'routine',
  target_minutes INTEGER NOT NULL,
  received_at TIMESTAMPTZ NOT NULL,
  assigned_at TIMESTAMPTZ,
  reported_at TIMESTAMPTZ,
  actual_minutes INTEGER,
  breached BOOLEAN DEFAULT FALSE,
  breach_reason TEXT,
  escalated_to TEXT,
  radiologist_name TEXT,
  notes TEXT,
  status TEXT DEFAULT 'tracking',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_sla_alerts_tenant ON sla_alerts(tenant_id);
CREATE INDEX IF NOT EXISTS idx_sla_alerts_breached ON sla_alerts(tenant_id, breached);

-- 9. Reading Worklist (Teleradiology Queue)
CREATE TABLE IF NOT EXISTS reading_worklists (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
  tenant_id TEXT NOT NULL,
  client_center_id TEXT,
  client_name TEXT,
  accession_number TEXT NOT NULL,
  patient_name TEXT,
  patient_age INTEGER,
  patient_gender TEXT,
  modality TEXT,
  body_part TEXT,
  study_description TEXT,
  series_count INTEGER,
  image_count INTEGER,
  priority TEXT DEFAULT 'routine',
  priority_order INTEGER DEFAULT 4,
  clinical_history TEXT,
  referring_doctor TEXT,
  received_at TIMESTAMPTZ NOT NULL,
  assigned_to TEXT,
  assigned_at TIMESTAMPTZ,
  report_started_at TIMESTAMPTZ,
  report_completed_at TIMESTAMPTZ,
  report_delivered_at TIMESTAMPTZ,
  sla_deadline TIMESTAMPTZ,
  critical_finding BOOLEAN DEFAULT FALSE,
  critical_finding_comm TEXT,
  report_text TEXT,
  addendum TEXT,
  notes TEXT,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_reading_worklists_tenant ON reading_worklists(tenant_id);
CREATE INDEX IF NOT EXISTS idx_reading_worklists_status ON reading_worklists(tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_reading_worklists_priority ON reading_worklists(tenant_id, priority);

-- 10. Cath Lab Schedule (SCAI/CSI)
CREATE TABLE IF NOT EXISTS cath_lab_schedules (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
  tenant_id TEXT NOT NULL,
  patient_id TEXT,
  patient_name TEXT NOT NULL,
  patient_age INTEGER,
  patient_gender TEXT,
  procedure_type TEXT NOT NULL,
  indication TEXT,
  diagnosis TEXT,
  scheduled_date TIMESTAMPTZ NOT NULL,
  scheduled_slot TEXT,
  lab_room TEXT,
  cardiologist TEXT,
  assistant_doctor TEXT,
  scrub_nurse TEXT,
  technician_name TEXT,
  anesthesiologist TEXT,
  consent_signed BOOLEAN DEFAULT FALSE,
  lab_work_done BOOLEAN DEFAULT FALSE,
  creatinine DOUBLE PRECISION,
  inr DOUBLE PRECISION,
  hb DOUBLE PRECISION,
  blood_group_confirmed BOOLEAN DEFAULT FALSE,
  npo_status TEXT,
  allergies TEXT,
  access_site TEXT DEFAULT 'radial',
  sheath_size TEXT,
  stent_used TEXT,
  stent_size TEXT,
  stent_brand TEXT,
  stent_lot_number TEXT,
  balloon_used TEXT,
  balloon_size TEXT,
  guidewire_used TEXT,
  catheter_used TEXT,
  contrast_used TEXT,
  contrast_volume_ml DOUBLE PRECISION,
  fluoro_time_min DOUBLE PRECISION,
  radiation_dose_mgy DOUBLE PRECISION,
  door_time TIMESTAMPTZ,
  balloon_time TIMESTAMPTZ,
  door_to_balloon_min INTEGER,
  procedure_start TIMESTAMPTZ,
  procedure_end TIMESTAMPTZ,
  outcome TEXT,
  complications TEXT,
  post_procedure_plan TEXT,
  discharge_date TIMESTAMPTZ,
  notes TEXT,
  status TEXT DEFAULT 'scheduled',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_cath_lab_tenant ON cath_lab_schedules(tenant_id);
CREATE INDEX IF NOT EXISTS idx_cath_lab_type ON cath_lab_schedules(tenant_id, procedure_type);

-- ============================================
-- DONE — 10 tables created
-- ============================================
